version: 1.2
workflows:
   - subclass: CWL
     primaryDescriptorPath: /refget_compliance_suite.cwl
     testParameterFiles:
     - /refget_compliance_suite_config.cwl.json
   - subclass: WDL
     primaryDescriptorPath: /refget_compliance_suite.wdl
     testParameterFiles:
     - /refget_compliance_suite_config.wdl.json

