site_name: Compliance Documentation
site_description: Compliance Documentation for Reference Sequence Retrieval APIs
site_author: GA4GH

repo_url: https://github.com/ga4gh/gsoc2018-ref-retrieval-api/

pages:
    - 'Preamble': 'index.md'
    - 'API Specification': 'api_spec.md'
    - 'Test Sequeces': 'test_sequences.md'
    - 'GET Sequence API':
        - 'Success Conditions': 'GET_sequence_API/success.md'
        - 'Error Conditions': 'GET_sequence_API/errors.md'
    - 'GET Metadata API': 'metadata.md'

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list

theme:
  name: 'readthedocs'
